name       : perl-extutils-helpers
version    : 0.026
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz : de901b6790a4557cf4ec908149e035783b125bf115eb9640feb1bc1c24c33416
license    : Artistic-2.0
component  : programming.perl
summary    : Various portability utilities for module builders
description: |
    Various portability utilities for module builders
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
